[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./"}]
ffi = true
solc = '0.8.17'


[fmt]
line_length = 150
# See more config options https://github.com/foundry-rs/foundry/tree/master/config